server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bunnyroom
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yyc
    password: yyc

mybatis:
  mapper-locations: mapper/*.xml

